### ISSUE TITLE
RuntimeError: All elements must be greater than (p-1)/2

### ISSUE THREAD

**Issue by AlexeySrus** [BGU-CS-VIL/DeepDPM#13]
Dear authors, I tried to use your implementation in research proposes and faced error in training process.
I want to cluster vectors of SIFT descriptors (image keypoints). To this I packed data which same to your examples (you could download it with the following link: https://drive.google.com/file/d/17TqIZLtlmSI2jiPl-haLE-_gpVVWoXhp/view?usp=sharing). As labels, I used results of kmeans algorithm from scikit-learn.
I tried to train model without and with initial clusters count (--init_k=100) and faced the following error:
```
Evaluating...
Epoch 55:  77%|███████████████████████████████████████▏           | 3907/5079 [01:40<00:30, 38.90it/s, loss=0.238, v_num=]
Traceback (most recent call last):                                                                                        
  File "DeepDPM.py", line 457, in <module>
    train_cluster_net()
  File "DeepDPM.py", line 442, in train_cluster_net
    trainer.fit(model, train_loader, val_loader)
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 560, in run_training_epoch
    self.trainer.logger_connector.log_train_epoch_end_metrics(
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 415, in log_train_epoch_end_metrics
    self.training_epoch_end(model, epoch_output, num_optimizers)
  File "/home/alexey/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 466, in training_epoch_end
    epoch_output = model.training_epoch_end(epoch_output)
  File "/home/alexey/programming/upwork/duplicates_filter/visual_matching_model/DeepDPM/src/clustering_models/clusternet_modules/clusternetasmodel.py", line 492, in training_epoch_end
    split_decisions = split_step(
  File "/home/alexey/programming/upwork/duplicates_filter/visual_matching_model/DeepDPM/src/clustering_models/clusternet_modules/utils/clustering_utils/split_merge_operations.py", line 157, in split_step
    split_rule(
  File "/home/alexey/programming/upwork/duplicates_filter/visual_matching_model/DeepDPM/src/clustering_models/clusternet_modules/utils/clustering_utils/split_merge_operations.py", line 106, in split_rule
    log_ll_k = prior.log_marginal_likelihood(codes_k, mus[k])
  File "/home/alexey/programming/upwork/duplicates_filter/visual_matching_model/DeepDPM/src/clustering_models/clusternet_modules/utils/clustering_utils/priors.py", line 66, in log_marginal_likelihood
    return self.mus_covs_prior.log_marginal_likelihood(codes_k, mu_k)
  File "/home/alexey/programming/upwork/duplicates_filter/visual_matching_model/DeepDPM/src/clustering_models/clusternet_modules/utils/clustering_utils/priors.py", line 165, in log_marginal_likelihood
    - mvlgamma(torch.tensor(self.niw_nu) / 2.0, D)
RuntimeError: All elements must be greater than (p-1)/2
```

Can you suggest what is the problem?

I used the following command to run training:
`python3 DeepDPM.py --dataset smallsift --latent_dim 128 --offline --gpus 0 --save_checkpoints=True --dir pretrained_embeddings/MOCO/`

Best regards, Alexey

**Comment by MengXinChengXuYuan** [comment]
prior_nu should be larger than latent_dim

**Comment by meitarronen** [comment]
@MengXinChengXuYuan  Thank you, you are correct :)
If your data is in dim D you should set --prior_nu to at least D + 1.

I'll add a code snip that checks it in the next code update.

**Comment by AlexeySrus** [comment]
Thanks!
