### ISSUE TITLE
`IndexError` from `plotting_utils`

### ISSUE THREAD

**Issue by RiccardoLincetto** [BGU-CS-VIL/DeepDPM#27]
When training with the command
```
python3 DeepDPM.py --dataset=synthetic --latent_dim=2 --init_k=15 --log_emb=every_n_epochs --log_emb_every=20 --offline --gpus=0
```
I consistently get the following error:
```
Evaluating...                                                                                                                                               
NMI : 0.9436628028368107, ARI: 0.9035767324812444, ACC: 0.9316, current K: 18
Epoch 60:  50%|████████████████████████████████████████████                                            | 79/158 [00:06<00:06, 11.52it/s, loss=0.252, v_num=]
Traceback (most recent call last):
  File "DeepDPM.py", line 441, in <module>
    train_cluster_net()
  File "DeepDPM.py", line 426, in train_cluster_net
    trainer.fit(model, train_loader, val_loader)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 560, in run_training_epoch
    self.trainer.logger_connector.log_train_epoch_end_metrics(
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 415, in log_train_epoch_end_metrics
    self.training_epoch_end(model, epoch_output, num_optimizers)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 466, in training_epoch_end
    epoch_output = model.training_epoch_end(epoch_output)
  File "/home/riccardo/DeepDPM/src/clustering_models/clusternet_modules/clusternetasmodel.py", line 551, in training_epoch_end
    self.plot_utils.plot_cluster_and_decision_boundaries(samples=self.codes, labels=self.train_resp.argmax(-1), gt_labels=self.train_gt, net_centers=self.mus, net_covs=self.covs, n_epoch=self.current_epoch, cluster_net=self)
  File "/home/riccardo/DeepDPM/src/clustering_models/clusternet_modules/utils/plotting_utils.py", line 336, in plot_cluster_and_decision_boundaries
    self.plot_clusters(
  File "/home/riccardo/DeepDPM/src/clustering_models/clusternet_modules/utils/plotting_utils.py", line 263, in plot_clusters
    samples[:, 0], samples[:, 1], c=self.colors[labels, :], s=40, alpha=0.5, zorder=1
IndexError: index 16 is out of bounds for dimension 0 with size 15
```
I'm not sure whether this could be connected with #25.

**Comment by RiccardoLincetto** [comment]
And changing the number of initial cluster to 3 I still get on epoch 60
```
NMI : 0.7896579961678791, ARI: 0.508700189172607, ACC: 0.4101, current K: 6
Epoch 60:  50%|████████████████████████████████████████████▌                                            | 79/158 [00:03<00:03, 24.36it/s, loss=1.91, v_num=]
Traceback (most recent call last):
  File "DeepDPM.py", line 441, in <module>
    train_cluster_net()
  File "DeepDPM.py", line 426, in train_cluster_net
    trainer.fit(model, train_loader, val_loader)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 560, in run_training_epoch
    self.trainer.logger_connector.log_train_epoch_end_metrics(
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 415, in log_train_epoch_end_metrics
    self.training_epoch_end(model, epoch_output, num_optimizers)
  File "/home/riccardo/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 466, in training_epoch_end
    epoch_output = model.training_epoch_end(epoch_output)
  File "/home/riccardo/DeepDPM/src/clustering_models/clusternet_modules/clusternetasmodel.py", line 551, in training_epoch_end
    self.plot_utils.plot_cluster_and_decision_boundaries(samples=self.codes, labels=self.train_resp.argmax(-1), gt_labels=self.train_gt, net_centers=self.mus, net_covs=self.covs, n_epoch=self.current_epoch, cluster_net=self)
  File "/home/riccardo/DeepDPM/src/clustering_models/clusternet_modules/utils/plotting_utils.py", line 336, in plot_cluster_and_decision_boundaries
    self.plot_clusters(
  File "/home/riccardo/DeepDPM/src/clustering_models/clusternet_modules/utils/plotting_utils.py", line 263, in plot_clusters
    samples[:, 0], samples[:, 1], c=self.colors[labels, :], s=40, alpha=0.5, zorder=1
IndexError: index 5 is out of bounds for dimension 0 with size 3
```

**Comment by meitarronen** [comment]
@RiccardoLincetto Thank you for your comment!
We will push a fixed to this bug soon

**Comment by meitarronen** [comment]
@RiccardoLincetto In the last update of the code this bug has been fixed. Please let us know if it persists!
