### ISSUE TITLE
Are DeepDPM dependencies compatible with recent GPUs ?

### ISSUE THREAD

**Issue by vdet** [BGU-CS-VIL/DeepDPM#31]
Hello,

We are trying to run the test code of DeepDPM on RTX 3090 and RTX A5000. 

We created a singularity VM with the dependencies listed in 
[https://github.com/BGU-CS-VIL/DeepDPM/blob/main/requirements.txt](https://github.com/BGU-CS-VIL/DeepDPM/blob/main/requirements.txt)
Then, from this VM, ran the test code:
```
Singularity> python3 DeepDPM.py --gpus 1 --offline --dataset synthetic --log_emb every_n_epochs --log_emb_every 1
Sequential()
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:145: UserWarning:
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

  | Name              | Type              | Params
--------------------------------------------------------
0 | cluster_net       | MLP_Classifier    | 201  
1 | subclustering_net | Subclustering_net | 252  
--------------------------------------------------------
453       Trainable params
0         Non-trainable params
453       Total params
0.002     Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                                                              | 0/158 [00:00<?, ?it/s]/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: training_step returned None if it was on purpose, ignore this warning...
  warnings.warn(*args, **kwargs)
Epoch 0:  50%|█████████████████████████████████████████████████████████████████████████                                                                         | 79/158 [00:00<00:00, 240.26it/s, loss=nan, v_num=]Initializing clusters params using Kmeans...
Epoch 0:  51%|██████████████████████████████████████████████████████████████████████████▍                                                                        | 80/158 [00:02<00:02, 33.51it/s, loss=nan, v_num=]
Traceback (most recent call last):                                                                                                                                                           | 0/79 [00:00<?, ?it/s]
  File "DeepDPM.py", line 448, in <module>
    train_cluster_net()
  File "DeepDPM.py", line 428, in train_cluster_net
    trainer.fit(model, train_loader, val_loader)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/training_loop.py", line 577, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 726, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/evaluation_loop.py", line 166, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 177, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 131, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/mnt/iribhm/people/zzhang/DeepDPM/DeepDPM-main_vincent/src/clustering_models/clusternet_modules/clusternetasmodel.py", line 268, in validation_step
    logits = self.cluster_net(codes)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/iribhm/people/zzhang/DeepDPM/DeepDPM-main_vincent/src/clustering_models/clusternet_modules/models/Classifiers.py", line 59, in forward
    x = F.relu(self.class_fc1(x))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Next, we tried to run DeepDPM from a VM we routinely use with RTX 3090 and RTX A5000 GPUs, which rest on more recent libraries versions. Not too surprisingly this failed:
```
python3 DeepDPM.py --gpus 0 --offline --dataset synthetic --log_emb every_n_epochs --log_emb_every 1
2022-08-12 13:26:04.514401: W tensorflow/stream_executor/platform/default/[dso_loader.cc:64](http://dso_loader.cc:64/)] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
2022-08-12 13:26:04.514479: I tensorflow/stream_executor/cuda/[cudart_stub.cc:29](http://cudart_stub.cc:29/)] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "DeepDPM.py", line 19, in <module>
    from src.clustering_models.clusternet_modules.clusternetasmodel import ClusterNetModel
  File "/mnt/iribhm/people/zzhang/DeepDPM/DeepDPM-main_vincent/src/clustering_models/clusternet_modules/clusternetasmodel.py", line 17, in <module>
    from src.clustering_models.clusternet_modules.utils.plotting_utils import PlotUtils
  File "/mnt/iribhm/people/zzhang/DeepDPM/DeepDPM-main_vincent/src/clustering_models/clusternet_modules/utils/plotting_utils.py", line 8, in <module>
    import umap
  File "/usr/local/lib/python3.8/dist-packages/umap/__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "/usr/local/lib/python3.8/dist-packages/umap/umap_.py", line 28, in <module>
    import numba
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less
```

Any advice to fix this issue?

All the best,

Vincent

**Comment by meitarronen** [comment]
Hi,

We tried running our code on RTX 3090 and it ran smoothly...
Can you please try create an environment with the requirements as they are listed in the readme file? (maybe there was a problem with generating the requirement file?)

Let us know how it goes...

**Comment by vdet** [comment]
Hello,

We needed cuda >= 11.3 and finally managed to run your demo command in GPU mode with the latest pytorch/cuda installs and only a minor fixe:
```
    trainer = pl.Trainer(logger=logger, max_epochs=args.max_epochs, gpus=args.gpus, num_sanity_val_steps=0, checkpoint_callback=checkpoint_callback, limit_train_batches=args.limit_train_batches, limit_val_batches=args.limit_val_batches)
```
changed to 
```
   trainer = pl.Trainer(logger=logger, max_epochs=args.max_epochs, accelerator='gpu', devices=args.gpus, num_sanity_val_steps=0, callbacks=checkpoint_callback,limit_train_batches=args.limit_train_batches, limit_val_batches=args.limit_val_batches)
```
to accommodate a recent Pytorch Lighting update.

We still get a few 'deprecated' warnings, but nothing preventing us to run the code.

Thanks for your reply !

Vincent
