### ISSUE TITLE
Invalid Covariance Matrix Error in DeepDPM_alternations.py

### ISSUE THREAD

**Issue by ShichangZh** [BGU-CS-VIL/DeepDPM#4]
Hello,

Thank you for the amazing work and for publishing the code.

I encountered the following error when running the `DeepDPM_alternations.py` script on MNIST.

The command I used is the following (copied from the example only with --dir different and --offline added):

```
python DeepDPM_alternations.py --latent_dim 10 --dataset mnist --lambda_ 0.005 --lr 0.002 --init_k 3 --train_cluster_net 200 --alternate --init_cluster_net_using_centers --reinit_net_at_alternation --dir ./dataset/ --pretrain_path ./saved_models/ae_weights/mnist_e2e.zip --number_of_ae_alternations 3 --transform None --log_metrics_at_train True --gpus 1 --epoch 1 --offline
```
The error I got is the following. I tried several times, and the error always happened around iteration 30 - 33.

```
Evaluating...
Epoch 30: 100%|█████████| 548/548 [00:17<00:00, 30.63it/s, loss=0.00362, v_num=]
Epoch 31:  86%|███████▋ | 469/548 [00:14<00:02, 31.33it/s, loss=0.00345, v_num=]Evaluating...
NMI : 0.49259220412522065, ARI: 0.28473904520954585, ACC: 0.30912, current K: 3
Validating: 0it [00:00, ?it/s]
Epoch 31:  86%|███████▋ | 470/548 [00:15<00:02, 30.05it/s, loss=0.00345, v_num=]
Epoch 0:   0%|                                          | 0/548 [07:41<?, ?it/s]
Traceback (most recent call last):
  File "/home/shichang/paper_reproduce/DeepDPM/DeepDPM_alternations.py", line 202, in <module>
    trainer.fit(model, train_loader, val_loader)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 633, in run_train
    self.train_loop.on_train_epoch_start(epoch)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 203, in on_train_epoch_start
    self.trainer.call_hook("on_train_epoch_start")
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1102, in call_hook
    output = hook_fx(*args, **kwargs)
  File "/home/shichang/paper_reproduce/DeepDPM/src/AE_ClusterPipeline.py", line 250, in on_train_epoch_start
    self._init_clusters()
  File "/home/shichang/paper_reproduce/DeepDPM/src/AE_ClusterPipeline.py", line 121, in _init_clusters
    self.clustering.init_cluster(self.train_dataloader(), self.val_dataloader(), logger=self.logger, centers=centers, init_num=self.init_clusternet_num)
  File "/home/shichang/paper_reproduce/DeepDPM/src/clustering_models/clusternet.py", line 57, in init_cluster
    self.fit_cluster(train_loader, val_loader, logger, centers)
  File "/home/shichang/paper_reproduce/DeepDPM/src/clustering_models/clusternet.py", line 65, in fit_cluster
    self.model.fit(train_loader, val_loader, logger, self.args.train_cluster_net, centers=centers)
  File "/home/shichang/paper_reproduce/DeepDPM/src/clustering_models/clusternet_modules/clusternet_trainer.py", line 42, in fit
    cluster_trainer.fit(self.cluster_model, train_loader, val_loader)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 577, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 726, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 166, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 177, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 131, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/shichang/paper_reproduce/DeepDPM/src/clustering_models/clusternet_modules/clusternetasmodel.py", line 275, in validation_step
    cluster_loss = self.training_utils.cluster_loss_function(
  File "/home/shichang/paper_reproduce/DeepDPM/src/clustering_models/clusternet_modules/utils/training_utils.py", line 235, in cluster_loss_function
    gmm_k = MultivariateNormal(model_mus[k].double().to(device=self.device), model_covs[k].double().to(device=self.device))
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/torch/distributions/multivariate_normal.py", line 146, in __init__
    super(MultivariateNormal, self).__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/home/shichang/anaconda3/envs/deepdpm/lib/python3.9/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter covariance_matrix (Tensor of shape (10, 10)) of distribution MultivariateNormal(loc: torch.Size([10]), covariance_matrix: torch.Size([10, 10])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[ 0.5951,  0.0092,  0.2854,  0.0728, -0.2996,  0.1251, -0.1172, -0.0078,
          0.0765,  0.1235],
        [ 0.0092,  0.5513,  0.0643, -0.1219,  0.1693,  0.1630, -0.1415, -0.0218,
         -0.1041,  0.0764],
        [ 0.2854,  0.0643,  0.6676, -0.2186, -0.2203,  0.0510, -0.0280, -0.1126,
          0.1910,  0.1136],
        [ 0.0728, -0.1219, -0.2186,  0.8729, -0.1988, -0.1151, -0.0771,  0.1936,
         -0.1680,  0.1279],
        [-0.2996,  0.1693, -0.2203, -0.1988,  0.7979, -0.0535,  0.0689, -0.0186,
         -0.1713, -0.0783],
        [ 0.1251,  0.1630,  0.0510, -0.1151, -0.0535,  0.4169, -0.1412,  0.0098,
          0.0774,  0.1063],
        [-0.1172, -0.1415, -0.0280, -0.0771,  0.0689, -0.1412,  0.5972, -0.0558,
          0.0094, -0.0770],
        [-0.0078, -0.0218, -0.1126,  0.1936, -0.0186,  0.0098, -0.0558,  0.4313,
          0.0730,  0.0873],
        [ 0.0765, -0.1041,  0.1910, -0.1680, -0.1713,  0.0774,  0.0094,  0.0730,
          0.6265,  0.0646],
        [ 0.1235,  0.0764,  0.1136,  0.1279, -0.0783,  0.1063, -0.0770,  0.0873,
          0.0646,  0.4388]], device='cuda:1', dtype=torch.float64)
```

**Comment by meitarronen** [comment]
Thank you for your interest in our work!
I haven't been able to reproduce the error that you sent yet.

Could you perhaps:
1. Send more details - I see that the error occurs after 30 epochs, and then the epoch number is 0. Is it right after the alternation? You could check that using the " initializing clusters" print
2. Try running without the --epoch flag and let us know if it resolves the issue? (e.g.: 
python DeepDPM_alternations.py --latent_dim 10 --dataset mnist --lambda_ 0.005 --lr 0.002 --init_k 3 --train_cluster_net 200 --alternate --init_cluster_net_using_centers --reinit_net_at_alternation --dir ./dataset/ --pretrain_path ./saved_models/ae_weights/mnist_e2e.zip --number_of_ae_alternations 3 --transform None --log_metrics_at_train True --gpus 1  --offline

**Comment by ShichangZh** [comment]
Thank you so much for the response! 

For your point 2, I copied and ran the command you provided and ended up with the same error, so remove --epoch didn't help for my case.

For your point 1, I am not quite sure which step it is actually. I saw there was an "initializing clusters" at the beginning with Kmeans (pasted at the end), but there doesn't seem to be other "initializing clusters". Besides, I have only seen Alternation 0 printed, meaning that the `self.init_clusternet_num` in  ``` Alternation {self.init_clusternet_num}: Running DeepDPM clustering ``` never evaluated to 1. I guess that means the alternation hasn't started? Also, according to the error message in my last comment, seems like the error occured at the validation step of the trainer? 

Not sure if these are helpful. Please let me know if you need more information.

Below is the log at the beginning, with the "initializing clusters" printed. After this was Epoch 2- 31 and then the error message I showed in the last comment.
```
Initializing clusters params using Kmeans...
running k-means on cpu..

[running kmeans]: 0it [00:00, ?it/s]
[running kmeans]: 0it [00:00, ?it/s, center_shift=28.364769, iteration=1, tol=0.000100]
[running kmeans]: 1it [00:00, 12.75it/s, center_shift=0.942527, iteration=2, tol=0.000100]
[running kmeans]: 2it [00:00, 22.48it/s, center_shift=0.415794, iteration=3, tol=0.000100]
[running kmeans]: 3it [00:00, 30.50it/s, center_shift=0.315685, iteration=4, tol=0.000100]
[running kmeans]: 4it [00:00, 36.52it/s, center_shift=0.148565, iteration=5, tol=0.000100]
[running kmeans]: 5it [00:00, 45.62it/s, center_shift=0.148565, iteration=5, tol=0.000100]
[running kmeans]: 5it [00:00, 45.62it/s, center_shift=0.053451, iteration=6, tol=0.000100]
[running kmeans]: 6it [00:00, 45.62it/s, center_shift=0.030316, iteration=7, tol=0.000100]
[running kmeans]: 7it [00:00, 45.62it/s, center_shift=0.021371, iteration=8, tol=0.000100]
[running kmeans]: 8it [00:00, 45.62it/s, center_shift=0.016619, iteration=9, tol=0.000100]
[running kmeans]: 9it [00:00, 45.62it/s, center_shift=0.013421, iteration=10, tol=0.000100]
[running kmeans]: 10it [00:00, 45.62it/s, center_shift=0.010539, iteration=11, tol=0.000100]
[running kmeans]: 11it [00:00, 45.62it/s, center_shift=0.009321, iteration=12, tol=0.000100]
[running kmeans]: 12it [00:00, 45.62it/s, center_shift=0.007064, iteration=13, tol=0.000100]
[running kmeans]: 13it [00:00, 45.62it/s, center_shift=0.005357, iteration=14, tol=0.000100]
[running kmeans]: 14it [00:00, 45.62it/s, center_shift=0.005096, iteration=15, tol=0.000100]
[running kmeans]: 15it [00:00, 73.70it/s, center_shift=0.005096, iteration=15, tol=0.000100]
[running kmeans]: 15it [00:00, 73.70it/s, center_shift=0.004896, iteration=16, tol=0.000100]
[running kmeans]: 16it [00:00, 73.70it/s, center_shift=0.004535, iteration=17, tol=0.000100]
[running kmeans]: 17it [00:00, 73.70it/s, center_shift=0.003931, iteration=18, tol=0.000100]
[running kmeans]: 18it [00:00, 73.70it/s, center_shift=0.003410, iteration=19, tol=0.000100]
[running kmeans]: 19it [00:00, 73.70it/s, center_shift=0.003555, iteration=20, tol=0.000100]
[running kmeans]: 20it [00:00, 73.70it/s, center_shift=0.002266, iteration=21, tol=0.000100]
[running kmeans]: 21it [00:00, 73.70it/s, center_shift=0.001888, iteration=22, tol=0.000100]
[running kmeans]: 22it [00:00, 73.70it/s, center_shift=0.001431, iteration=23, tol=0.000100]
[running kmeans]: 23it [00:00, 73.70it/s, center_shift=0.001265, iteration=24, tol=0.000100]
[running kmeans]: 24it [00:00, 73.70it/s, center_shift=0.000857, iteration=25, tol=0.000100]
[running kmeans]: 25it [00:00, 84.77it/s, center_shift=0.000857, iteration=25, tol=0.000100]
[running kmeans]: 25it [00:00, 84.77it/s, center_shift=0.000601, iteration=26, tol=0.000100]
[running kmeans]: 26it [00:00, 84.77it/s, center_shift=0.000579, iteration=27, tol=0.000100]
[running kmeans]: 27it [00:00, 84.77it/s, center_shift=0.000351, iteration=28, tol=0.000100]
[running kmeans]: 28it [00:00, 84.77it/s, center_shift=0.000257, iteration=29, tol=0.000100]
[running kmeans]: 29it [00:00, 84.77it/s, center_shift=0.000293, iteration=30, tol=0.000100]
[running kmeans]: 30it [00:00, 84.77it/s, center_shift=0.000324, iteration=31, tol=0.000100]
[running kmeans]: 31it [00:00, 84.77it/s, center_shift=0.000175, iteration=32, tol=0.000100]
[running kmeans]: 32it [00:00, 84.77it/s, center_shift=0.000120, iteration=33, tol=0.000100]
[running kmeans]: 33it [00:00, 84.77it/s, center_shift=0.000101, iteration=34, tol=0.000100]
[running kmeans]: 34it [00:00, 84.77it/s, center_shift=0.000101, iteration=35, tol=0.000100]
[running kmeans]: 35it [00:00, 88.94it/s, center_shift=0.000101, iteration=35, tol=0.000100]
[running kmeans]: 36it [00:00, 83.32it/s, center_shift=0.000079, iteration=36, tol=0.000100]

Validating: 0it [00:00, ?it/s]
Validating:   0%|                                        | 0/79 [00:00<?, ?it/s]
Epoch 0:  86%|████████████  | 471/548 [00:04<00:00, 97.25it/s, loss=nan, v_num=]
Epoch 0:  90%|████████████▌ | 491/548 [00:04<00:00, 99.33it/s, loss=nan, v_num=]
Epoch 0:  94%|████████████▏| 516/548 [00:05<00:00, 102.29it/s, loss=nan, v_num=]
Epoch 0: 100%|█████████████| 548/548 [00:05<00:00, 105.04it/s, loss=nan, v_num=]
Epoch 1:  86%|██████████▎ | 469/548 [00:06<00:01, 74.40it/s, loss=0.106, v_num=]Evaluating...
NMI : 0.3229948133907757, ARI: 0.19309345777211237, ACC: 0.28623, current K: 3
Epoch 1:  86%|██████████▎ | 470/548 [00:38<00:06, 12.35it/s, loss=0.106, v_num=]
Validating: 0it [00:00, ?it/s]
Validating:   0%|                                        | 0/79 [00:00<?, ?it/s]
Epoch 1:  86%|██████████▎ | 471/548 [00:38<00:06, 12.27it/s, loss=0.106, v_num=]

```

**Comment by meitarronen** [comment]
As the problem happens at the validation step (and not the training step) it seems like it happens after a split/merge step but I cannot see it in the logs. Could you please output the entire logging to a txt file and send it here? 
(by e.g. running "python DeepDPM_alternations.py .... > out.txt").

**Comment by ShichangZh** [comment]
Thank you so much for your response. The file below contains the entire logging generated in the way you suggested. The error message wasn't logged though, but it was the same as my initial comment.

[out.txt](https://github.com/BGU-CS-VIL/DeepDPM/files/8593171/out.txt)

**Comment by metaisallyouneed** [comment]
> Thank you so much for your response. The file below contains the entire logging generated in the way you suggested. The error message wasn't logged though, but it was the same as my initial comment.
> 
> [out.txt](https://github.com/BGU-CS-VIL/DeepDPM/files/8593171/out.txt)

Hi,
I got the same error. It happened at different EPs when I run "python DeepDPM_alternations.py " iteratively.
Did you figure it out?

**Comment by meitarronen** [comment]
Just an update - we are working on a fix for this - will be updated soon.

**Comment by blakechi** [comment]
Hello,

I also got the same error as well. Just want to check whether this issue has been fixed? 
And if possible, could authors (@meitarronen) also share what's going wrong in the implementation?

Thanks!

**Comment by shwetakatti98** [comment]
Hey,

Thank you for all the work. I have been facing a similar issue and would like to know if there will be an update regarding this anytime soon?

Thanks :)

**Comment by meitarronen** [comment]
Hi,

It is coming soon!
We are working on it and will update once it is up :)

‫בתאריך יום ו׳, 15 ביולי 2022 ב-18:46 מאת ‪Shweta Katti‬‏ <‪
***@***.***‬‏>:‬

**Comment by meitarronen** [comment]
@shwetakatti98 @blakechi @LifelongReID @ShichangZh 
Please take a look at the last update of the code, the issues should be fixed :)

**Comment by meitarronen** [comment]
Closing this for now, let us know if this issue persists!

**Comment by npikki** [comment]
Hi! I have just run into exactly the same issue, using parameters specified in README and dependencies from the requirements file (expect for numpy 1.21 instead of 1.20: otherwise it seems incompatible with pandas version 1.4), could you please reopen the issue? Thanks!
