### ISSUE TITLE
AttributeError: 'ClusterNet' object has no attribute 'model'

### ISSUE THREAD

**Issue by Huiyu-Li** [BGU-CS-VIL/DeepDPM#54]
I try to pre-train the model on MINIST dataset, but I got the **AttributeError: 'ClusterNet' object has no attribute 'model'** .  It seems that the ClusterNet model fails to call the def init_cluster() to initialize the self.model = ClusterNetTrainer(). Below is the traceback of the error. Could you help me to fix this?

Epoch 0:   0%|                                           | 0/548 [00:00<?, ?it/s]  
========== Start pretraining ==========
Epoch 0:  70%|██▊ | 384/548 [09:47<04:10,  1.53s/it, loss=2.49e+04, v_num=]        Epoch 1:  28%|███        | 153/548 [01:59<05:08,  1.28it/s, loss=2.23e+04, v_num=] Epoch 2:  65%|████▌  | 354/548 [09:07<04:59,  1.55s/it, loss=1.95e+04, v_num=]     
Epoch 2: 100%|████████████| 548/548 [12:13<00:00,  1.34s/it, loss=1.88e+04, v_num=]
Traceback (most recent call last):
  File "/home/huili/Projects/DeepDPM_Original/DeepDPM_alternations.py", line 236, in <module>
    train_clusternet_with_alternations()
  File "/home/huili/Projects/DeepDPM_Original/DeepDPM_alternations.py", line 208, in train_clusternet_with_alternations
    DeepDPM = model.clustering.model.cluster_model
AttributeError: 'ClusterNet' object has no attribute 'model'

**Comment by Huiyu-Li** [comment]
It has been resolved. 
There are two ways to avoid this error：
1. make sure that --pretrain_epochs is not in (5, 10, 15, 20, 25, 30, 35, 40, 50, 100, 500). 
2. let these two elif conditions in the order below, to make sure that the priority of "End pretraining" is higher than that of "Saving weights", so the training process would not skip calling  self._init_clusters()
elif self.current_epoch == self.args.pretrain_epochs and self.args.pretrain and self.pretrain:
            print("========== End pretraining ==========")
            self.pretrain = False
            print("Saving weights...")
            torch.save(self.state_dict(), f"./saved_models/{self.args.dataset}_{self.current_epoch}_{datetime.now()}")
            self._init_clusters()
        
        elif self.args.pretrain and self.pretrain and self.current_epoch in (5, 10, 15, 20, 25, 30, 35, 40, 50, 100, 500):
            print("Saving weights...")
            torch.save(self.state_dict(), f"./saved_models/{self.args.dataset}_{self.current_epoch}_{datetime.now()}")
